global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Add additional scrape configs for your backend services
  # - job_name: 'backend'
  #   static_configs:
  #     - targets: ['your-backend-service:port']