auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

storage_config:
  filesystem:
    directory: /loki/chunks

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

schema_config:
  configs:
    - from: 2020-01-01
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h