name: Application CI

on:
  push:
    branches:
      - 'integration'

permissions:
  contents: write  # Grants permission to push changes to the repository

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push Frontend
        working-directory: ./frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/challenge-frontend:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/challenge-frontend:${{ github.sha }}
      
      - name: Build and Push Backend
        working-directory: ./backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/challenge-backend:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/challenge-backend:${{ github.sha }}
      
      - name: Update docker-compose
        run: |
          sed -i 's/challenge-frontend:latest/challenge-frontend:${{ github.sha }}/g' docker-compose.yaml
          sed -i 's/challenge-backend:latest/challenge-backend:${{ github.sha }}/g' docker-compose.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docker-compose.yaml
          git commit -m "Update image tags"
          git push
